### ISSUE TITLE
Getter/setter customization

### ISSUE THREAD

**Issue by grigorig** [BigBahss/vscode-cmantic#11]
It would be very useful if alternative naming styles would be supported. Currently the extension always uses `getSomething` and `setSomething`, but other styles are used as well, for instance `get_something`/`set_something`.

**Comment by BigBahss** [comment]
Thanks for opening an issue, I should add a setting to control that. It will detect if the variable name is snake_case already and will generate names like `get_something`/`set_something`. However, the case-style cannot be determined from a name without any underscores, so a setting is probably preferable.

**Comment by BigBahss** [comment]
Added on branch `master`, leaving this open until a release is published.

Added a setting `Case Style` to control whether getters and setters are generated with names in snake_case, camelCase, or PascalCase.

**Comment by BigBahss** [comment]
Added in v0.4.2
