### ISSUE TITLE
Setter generation doesn't handle references properly

### ISSUE THREAD

**Issue by grigorig** [BigBahss/vscode-cmantic#12]
The setter generator generates a declaration like `void setSomething(const Something& &something)` for a member of type `Something&`, which is a syntax error.

**Comment by BigBahss** [comment]
Thank you for letting me know, that's something I did not account for. I'll get that fixed.

**Comment by BigBahss** [comment]
Fixed on branch `master`, leaving this open until a release is published.

I also noticed generating a getter for a reference data member will return a reference. Since I don't have experience with using reference data members, is this typical? Or should it just return the value?

**Comment by grigorig** [comment]
It needs to return a reference as classes might have a deleted copy constructor.

**Comment by BigBahss** [comment]
Gotcha, thank you!

**Comment by BigBahss** [comment]
Fixed in v0.4.2
